// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//<auto-generated />
namespace Org.Apache.REEF.Fluid.Message
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using Microsoft.Hadoop.Avro;

    /// <summary>
    /// Used to serialize and deserialize Avro record Org.Apache.REEF.Fluid.Message.RTaskMsg.
    /// </summary>
    [DataContract(Namespace = "Org.Apache.REEF.Fluid.Message")]
    public partial class RTaskMsg
    {
        private const string JsonSchema = @"{""type"":""record"",""name"":""Org.Apache.REEF.Fluid.Message.RTaskMsg"",""doc"":""Request to execute an R function with associated data on a REEF evaluator"",""fields"":[{""name"":""uuid"",""doc"":""Universially unique indentifier of the task."",""type"":""string""},{""name"":""function"",""doc"":""R function to be executed on a REEF evaluator."",""type"":""string""},{""name"":""data"",""doc"":""The data requried by the R function."",""type"":""string""}]}";

        /// <summary>
        /// Gets the schema.
        /// </summary>
        public static string Schema
        {
            get
            {
                return JsonSchema;
            }
        }
      
        /// <summary>
        /// Gets or sets the uuid field.
        /// </summary>
        [DataMember]
        public string uuid { get; set; }
              
        /// <summary>
        /// Gets or sets the function field.
        /// </summary>
        [DataMember]
        public string function { get; set; }
              
        /// <summary>
        /// Gets or sets the data field.
        /// </summary>
        [DataMember]
        public string data { get; set; }
                
        /// <summary>
        /// Initializes a new instance of the <see cref="RTaskMsg"/> class.
        /// </summary>
        public RTaskMsg()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RTaskMsg"/> class.
        /// </summary>
        /// <param name="uuid">The uuid.</param>
        /// <param name="function">The function.</param>
        /// <param name="data">The data.</param>
        public RTaskMsg(string uuid, string function, string data)
        {
            this.uuid = uuid;
            this.function = function;
            this.data = data;
        }
    }
}
