# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.initialize <- function(packageDirectory) {
    .Call('_Fluid_rcpp_initialize', PACKAGE = 'Fluid', packageDirectory)
}

.connect <- function(ipAddress, port) {
    .Call('_Fluid_rcpp_connect', PACKAGE = 'Fluid', ipAddress, port)
}

.disconnect <- function() {
    .Call('_Fluid_rcpp_disconnect', PACKAGE = 'Fluid')
}

.submitJob <- function(environment, dataFrame) {
    .Call('_Fluid_rcpp_submitJob', PACKAGE = 'Fluid', environment, dataFrame)
}

