//<auto-generated />
namespace org.apache.reef.bridge.message
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using Microsoft.Hadoop.Avro;

    /// <summary>
    /// Used to serialize and deserialize Avro record org.apache.reef.bridge.message.CLRInitialized.
    /// </summary>
    [DataContract(Namespace = "org.apache.reef.bridge.message")]
    public partial class CLRInitialized
    {
        private const string JsonSchema = @"{""type"":""record"",""name"":""org.apache.reef.bridge.message.CLRInitialized"",""doc"":""First message from the CLR side of the bridge after it connects to the Java side."",""fields"":[{""name"":""initialized"",""doc"":""Dummy payload"",""type"":""boolean""}]}";

        /// <summary>
        /// Gets the schema.
        /// </summary>
        public static string Schema
        {
            get
            {
                return JsonSchema;
            }
        }
      
        /// <summary>
        /// Gets or sets the initialized field.
        /// </summary>
        [DataMember]
        public bool initialized { get; set; }
                
        /// <summary>
        /// Initializes a new instance of the <see cref="CLRInitialized"/> class.
        /// </summary>
        public CLRInitialized()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CLRInitialized"/> class.
        /// </summary>
        /// <param name="initialized">The initialized.</param>
        public CLRInitialized(bool initialized)
        {
            this.initialized = initialized;
        }
    }
}
