//<auto-generated />
namespace org.apache.reef.bridge.message
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using Microsoft.Hadoop.Avro;

    /// <summary>
    /// Used to serialize and deserialize Avro record org.apache.reef.bridge.message.SystemOnStart.
    /// </summary>
    [DataContract(Namespace = "org.apache.reef.bridge.message")]
    public partial class SystemOnStart
    {
        private const string JsonSchema = @"{""type"":""record"",""name"":""org.apache.reef.bridge.message.SystemOnStart"",""doc"":""The SystemOnStart message is sent to the CLR bridge from the Java bridge when the round trip communication path has been established."",""fields"":[{""name"":""dateTime"",""type"":""int""}]}";

        /// <summary>
        /// Gets the schema.
        /// </summary>
        public static string Schema
        {
            get
            {
                return JsonSchema;
            }
        }
      
        /// <summary>
        /// Gets or sets the dateTime field.
        /// </summary>
        [DataMember]
        public int dateTime { get; set; }
                
        /// <summary>
        /// Initializes a new instance of the <see cref="SystemOnStart"/> class.
        /// </summary>
        public SystemOnStart()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SystemOnStart"/> class.
        /// </summary>
        /// <param name="dateTime">The dateTime.</param>
        public SystemOnStart(int dateTime)
        {
            this.dateTime = dateTime;
        }
    }
}
