//<auto-generated />
namespace org.apache.reef.bridge.message
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using Microsoft.Hadoop.Avro;

    /// <summary>
    /// Used to serialize and deserialize Avro record org.apache.reef.bridge.message.Protocol.
    /// </summary>
    [DataContract(Namespace = "org.apache.reef.bridge.message")]
    [KnownType(typeof(Dictionary<string, int>))]
    public partial class Protocol
    {
        private const string JsonSchema = @"{""type"":""record"",""name"":""org.apache.reef.bridge.message.Protocol"",""doc"":""Negotiate Java/C# bridge protocol identifiers."",""fields"":[{""name"":""classMap"",""doc"":""Map of message class names to header message identifier."",""type"":{""type"":""map"",""values"":""int""}}]}";

        /// <summary>
        /// Gets the schema.
        /// </summary>
        public static string Schema
        {
            get
            {
                return JsonSchema;
            }
        }
      
        /// <summary>
        /// Gets or sets the classMap field.
        /// </summary>
        [DataMember]
        public IDictionary<string, int> classMap { get; set; }
                
        /// <summary>
        /// Initializes a new instance of the <see cref="Protocol"/> class.
        /// </summary>
        public Protocol()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Protocol"/> class.
        /// </summary>
        /// <param name="classMap">The classMap.</param>
        public Protocol(IDictionary<string, int> classMap)
        {
            this.classMap = classMap;
        }
    }
}
